<a href="https://colab.research.google.com/github/rozbujnik1/data-science/blob/main/02_algebra_liniowa_moje_cwiczenia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
  import numpy as np

In [ ]:
v1 = np.array([-3,4])
v1

array([-3,  4])

In [ ]:
np.linalg.norm(v1)

5.0

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [ ]:
p = np.array([3,0,1])
q = np.array([0,4,2])

np.linalg.norm(p-q)

5.0990195135927845

#Mnożenie macierzy

In [ ]:
    X = np.array([[5,3],[3,9]])
    Y = np.array([[1],[-1]])

In [ ]:
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X,Y)

In [ ]:
Z

array([[ 2],
       [-6]])

In [ ]:
Z.shape

(2, 1)

In [ ]:
X = np.array([[2,-1,3],[3,1,0]])
Y = np.array([[2,1,-1],[0,-1,2],[3,2,0]])
print(X)
print(Y)

[[ 2 -1  3]
 [ 3  1  0]]
[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
  np.dot(X,Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

#Wyznacznik Macierzy

In [ ]:
A = np.array([[2,4],[-1,3]])
round(np.linalg.det(A))

10.0

In [ ]:
np.trace(A)

5

In [ ]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
np.set_printoptions(precision=4, suppress=True)
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [ ]:
T = A.T
T

array([[ 2, -1],
       [ 4,  3]])

In [3]:
A = np.array([[2, 4],[1,-1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [5]:
B = np.array([[10],[-1]])
B

array([[10],
       [-1]])

In [8]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.16666667,  0.66666667],
       [ 0.16666667, -0.33333333]])

In [9]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [10]:
X.shape

(2, 1)